APP_NAME = "Python一键打包EXE"
APP_AUTHOR = "Gu-0312"
APP_VERSION = "1.1.0"
APP_DESCRIPTION = "基于 PyInstaller 的 Python 一键打包工具"
APP_HOMEPAGE = "https://github.com/Gu-0312/PyKit"
APP_COPYRIGHT = f"Copyright (C) 2026 {APP_AUTHOR}"
